version: "3.6"
services:
  webserver:
    image: nginx:latest
    restart: unless-stopped
    container_name: market_docker_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD:/var/www/html
    ports:
      - 9999:80
    networks:
      - marketapp
  php:
    build: .
    restart: unless-stopped
    container_name: market_docker_php
    volumes:
      - $PWD:/var/www/html
    networks: 
      - marketapp
  db:
    image: mysql:5.7.22
    container_name: db_market
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: modesy
      MYSQL_ROOT_PASSWORD: adminlocal
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbmarket:/var/lib/mysql/
    networks:
      - marketapp
networks:
  marketapp:
    driver: bridge
volumes:
  dbmarket: